# Generated by Django 6.0.2 on 2026-02-25 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Zapato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('categoria', models.CharField(choices=[('Running', 'Running'), ('Lifestyle', 'Lifestyle'), ('Casual', 'Casual')], max_length=20)),
                ('descripcion', models.TextField()),
                ('imagen_url', models.URLField(max_length=500)),
                ('colores', models.CharField(help_text='Separados por coma', max_length=200)),
                ('materiales', models.CharField(max_length=200)),
            ],
        ),
    ]
